### PR TITLE
Making record section responsive

### PR DESCRIPTION
**Pull request by rutikgagare**
## 🛠️ Fixes Issue : "yes I have fixed the issue check the updated styling if anything else required let me know"

Fixed Issue 11

## 👨‍💻 Changes proposed: 

I have changed the styling of the class record-container and record

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.
- [x] I am a participant of Hacktoberfest 2023.

## 📄 Note to reviewers
I have made the record section responsive if any changes required please let me know.
please merge my PR

## 📷 Screenshots
Screenshot_722

### CODE REVIEW

**Comment by KiranAminPanjwani** [comment]
image

Thank you for the wonderful contribution. However, the "Personal Health Journal" section is repeated twice. Please remove the second occurrence.

**Comment by rutikgagare** [comment]
Okay I will do that

**Comment by rutikgagare** [comment]
yes I have updated it can you please merge my pull request

**Comment by KiranAminPanjwani** [comment]
Thank you for contributing!✨

**Pull request merged**
