### PR TITLE
CRUD feature using local storage

### LINKED ISSUE #114: [FEATURE] Storing data in local storage
### 🎇 Description

Hi, I saw you closed the Issue #83 of implementing MongoDB, but I would want to suggest adding a local storage property to store data. It will still stay with Vanilla Javasciprt and I think having multiple records saved in your browser will make the development eaiser for making things like grid layout, moving cards by drag and drop... or maybe connecting records to the progress bar.

Well then, I'll have to edit script.js.

Let me know and assign me if it's ok.

Thank you 😄 

### 🖼 Screenshots

_No response_

### PR DESCRIPTION
**Pull request by sunnydaysinseoul**
## 👨‍💻 Changes proposed: 

1. Changed 'Add Your Record' from button type to submit type (index.html)
2. Add Record to the localstorage
3. Delete Record from the screen and the localstorage
4. Edit Record from the screen and the localstorage
5. Draw saved data on the screen when the page is loaded
6. Deleted Static Record script (No more needed)

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.
- [x] I am a participant of Hacktoberfest 2023.

## 📷 Screenshots
screenshotPR
image -> updated icon including save button

### CODE REVIEW

**Comment by KiranAminPanjwani** [comment]
Hey,

Thank you so much for the wonderful contribution! ✨

However, the UI has been changed slightly. Please update your repository and adjust your changes accordingly. Your efforts in this regard would be much appreciated. :-)

**Comment by sunnydaysinseoul** [comment]
Ok😁

**Comment by sunnydaysinseoul** [comment]
Hi, just updated to match the updated design. (modals, button icons)

**Comment by KiranAminPanjwani** [comment]
Thank you for the wonderful contribution ✨

**Pull request merged**
