### PR TITLE
removed bug which adds empty record

### PR DESCRIPTION
**Pull request by BLSowmya**
## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.
- [x] I am a participant of Hacktoberfest 2023.

### CODE REVIEW

**Comment by BLSowmya** [comment]
i did not mention b ug number when reporting issue but i have changed code so that it cannot add empty record

**Comment by dipanshparmar** [comment]
@BLSowmya Empty spaces are still considered valid input.

**Comment by BLSowmya** [comment]
> @BLSowmya Empty spaces are still considered valid input.

If that's the case what is use of having records like this...there can be possibility and difficulty having more empty records and confused to select what records when making a decision....if we don't have time and date then we can have empty records to count but now we already have date

**Comment by dipanshparmar** [comment]
You didn't get my point. I acknowledged the change. I was just saying that you didn't completely fix the bug. If I enter some empty spaces in all the fields and hit `Add Your Record`, it still gets registered. This should not be happening. I was suggesting that you should handle this case as well.

**Comment by BLSowmya** [comment]
> You didn't get my point. I acknowledged the change. I was just saying that you didn't completely fix the bug. If I enter some empty spaces in all the fields and hit `Add Your Record`, it still gets registered. This should not be happening. I was suggesting that you should handle this case as well.

Ohh..is it ? Sure thing ...I will change it again

**Comment by BLSowmya** [comment]
@dipanshparmar would u mind checking once and let me know if there is anything i need to change?

**Comment by dipanshparmar** [comment]
LGTM! :+1:

**Comment by KiranAminPanjwani** [comment]
@BLSowmya Thank you so much for the wonderful contribution✨
@dipanshparmar Thank you for your amazing feedbacks.🙌

**Comment by BLSowmya** [comment]
> @BLSowmya Thank you so much for the wonderful contribution✨
> @dipanshparmar Thank you for your amazing feedbacks.🙌

Thank you for giving this opportunity and I will make sure completing the tasks u assigned

**Comment by KiranAminPanjwani** [comment]
The contribution is wonderful; however, we can still improve the "add to record" section. It currently accepts random inputs as well. We need a validation mechanism to determine whether the input is relevant or not. This will dictate the displayed status. Currently, it shows "poor" for every random input.

**Comment by dipanshparmar** [comment]
@KiranAminPanjwani Did you have a look at the live preview of the website? The commit [2913ae1](https://github.com/KiranAminPanjwani/MedStats/commit/2913ae1b4be312b0e9036c88858c73d051c24b33) duplicated the code.

**Comment by KiranAminPanjwani** [comment]
Yes, I just saw it. It is due to some wrong merges. Please give time  I'm resolving it

**Comment by KiranAminPanjwani** [comment]
@BLSowmya Okay, so for some reason, the code had become corrupted. Now, I kindly request you to please review the current pull request #43 and verify whether the current deployment incorporates the changes you made earlier or not. 
If you are unable to locate your changes, I would appreciate it if you could upgrade your forked repository and submit a new pull request. :-)

**Comment by BLSowmya** [comment]
> @BLSowmya Okay, so for some reason, the code had become corrupted. Now, I kindly request you to please review the current pull request #43 and verify whether the current deployment incorporates the changes you made earlier or not. 
> If you are unable to locate your changes, I would appreciate it if you could upgrade your forked repository and submit a new pull request. :-)

I have tested with empty inputs again and it is not accepting empty input so I think my code is working fine

**Comment by KiranAminPanjwani** [comment]
> > @BLSowmya Okay, so for some reason, the code had become corrupted. Now, I kindly request you to please review the current pull request #43 and verify whether the current deployment incorporates the changes you made earlier or not.
> > If you are unable to locate your changes, I would appreciate it if you could upgrade your forked repository and submit a new pull request. :-)
> 
> I have tested with empty inputs again and it is not accepting empty input so I think my code is working fine...If there is anything else please let me know

Awesome, keep contributing!!!🙌

**Pull request merged**
