### PR TITLE
Logo and Home added in Login Page

### LINKED ISSUE #58: Logo icon in Log-Out page is different & Home button
### 🎇 Description

Logo icon in log-out page is different from the original logo and also there should be a button in log-out's page navbar to navigate to the HOME PAGE.

**LOGO IN HOME PAGE**
Screenshot 2023-10-13 at 9 57 01 PM

**LOGO IN LOGOUT PAGE**
Screenshot 2023-10-13 at 9 57 25 PM

### 🖼 Screenshots

_No response_

### PR DESCRIPTION
**Pull request by JatinBawne**
fixes #58 

Logo in the home page is synched with home page's logo and Home button has been added in login  page's navbar.

Screenshot 2023-10-14 at 11 49 47 AM

### CODE REVIEW

**Comment by JatinBawne** [comment]
@KiranAminPanjwani I had some issues in the last PR that I raised, so new PR has been created.

kindly review and merge.

sorry fir the inconvenience

**Comment by KiranAminPanjwani** [comment]
Feedback:
If a user clicks on 'home' without logging in, the MedStats home page should display the 'login' option instead of 'logout'.

**Comment by JatinBawne** [comment]
> Feedback: If a user clicks on 'home' without logging in, the MedStats home page should display the 'login' option instead of 'logout'.

Done.

@KiranAminPanjwani  Kindly review and merge

**Comment by KiranAminPanjwani** [comment]
> Feedback: If a user clicks on 'home' without logging in, the MedStats home page should display the 'login' option instead of 'logout'.

This issue has been resolved. However, now, when a user logs in to MedStats and enters the MedStats homepage, the 'logout' option should be available

**Comment by JatinBawne** [comment]
> > Feedback: If a user clicks on 'home' without logging in, the MedStats home page should display the 'login' option instead of 'logout'.
> 
> This issue has been resolved. However, now, when a user logs in to MedStats and enters the MedStats homepage, the 'logout' option should be available

I understand your concern but there is not any validation for username and password.
to do that it will require few more modifications, for which I'll raise a new issue. 

Kindly merge this PR and let me raise issue for validation and login status.

**Comment by KiranAminPanjwani** [comment]
> > > Feedback: If a user clicks on 'home' without logging in, the MedStats home page should display the 'login' option instead of 'logout'.
> > 
> > 
> > This issue has been resolved. However, now, when a user logs in to MedStats and enters the MedStats homepage, the 'logout' option should be available
> 
> I understand your concern but there is not any validation for username and password. to do that it will require few more modifications, for which I'll raise a new issue.
> 
> Kindly merge this PR and let me raise issue for validation and login status.

Noted.

**Pull request merged**
