### PR TITLE
Cursor updated

### LINKED ISSUE #14: [Enhancement] The cursor should become pointer while hovering the 'Check Your Progress' checkpoints
### 🎇 Description

While hovering to the checkpoints under the 'Check You Progress' the cursor should change to POINTER to enhance the user experience.

### 🖼 Screenshots

https://github.com/KiranAminPanjwani/MedStats/assets/99788083/6e9e628f-202c-44f2-9eab-45941b23b9b6

### PR DESCRIPTION
**Pull request by JatinBawne**
Closes #14 

On hovering the checkpoints in the section 'CHECK YOUR PROGRESS' the cursor is changing to pointer .

### CODE REVIEW

**Comment by JatinBawne** [comment]
@KiranAminPanjwani  kindly merge

**Comment by KiranAminPanjwani** [comment]
Thank you for the contribution. Please upgrade your forked repository once.

**Comment by JatinBawne** [comment]
@KiranAminPanjwani Done, kindly merge

**Comment by KiranAminPanjwani** [comment]
Happy contributing.✨

**Pull request merged**
