### PR TITLE
Added footer to login and signup pages

### PR DESCRIPTION
**Pull request by NateNear**
## 👨‍💻 Changes proposed: 

Added footer to login and signup page.

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.
- [x] I am a participant of Hacktoberfest 2022.

## 📷 Screenshots
image
image

### CODE REVIEW

**Comment by NateNear** [comment]
@KiranAminPanjwani can you check the PR please.

**Comment by KiranAminPanjwani** [comment]
> @KiranAminPanjwani can you check the PR please.

Please mention you issue number in the comment.

**Comment by NateNear** [comment]
Issue #108

**Comment by KiranAminPanjwani** [comment]
Thank you for the contribution✨

**Pull request merged**
