### PR TITLE
Added ❌ button which deletes the record on clicking

### LINKED ISSUE #32: Add remove/edit option
### 🎇 Description

add remove record and edit record option so that if by mistake someone adds wrong details they can edit or delete it

### 🖼 Screenshots

_No response_

### PR DESCRIPTION
**Pull request by BLSowmya**
## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.
- [x] I am a participant of Hacktoberfest 2023.

### CODE REVIEW

**Comment by KiranAminPanjwani** [comment]
@BLSowmya Thank you for the wonderful contribution. Here is my feedback:

1. Please refrain from using the "x" button, as it may imply that the user can temporarily hide or minimize the record. Records are intended to be stored for the long term so that users can maintain a comprehensive history.
In cases where a user needs to remove an entry, it's better to implement a "dustbin symbol" to clearly indicate the delete option.
2. When the delete button is clicked, it's advisable to prompt the user with a confirmation dialogue box to ensure they indeed wish to delete it permanently.
3. It seems that the **edit** symbol attached to the records is not functioning as expected. I recommend looking into this functionality.
4. Currently, the cross button only seems to be operational for newly added records. If possible, I would suggest working on the functionality to ensure consistency across all records.

**Comment by BLSowmya** [comment]
> @BLSowmya Thank you for the wonderful contribution. Here is my feedback:
> 
> 1. Please refrain from using the "x" button, as it may imply that the user can temporarily hide or minimize the record. Records are intended to be stored for the long term so that users can maintain a comprehensive history.
> In cases where a user needs to remove an entry, it's better to implement a "dustbin symbol" to clearly indicate the delete option.
> 2. When the delete button is clicked, it's advisable to prompt the user with a confirmation dialogue box to ensure they indeed wish to delete it permanently.
> 3. It seems that the **edit** symbol attached to the records is not functioning as expected. I recommend looking into this functionality.
> 4. Currently, the cross button only seems to be operational for newly added records. If possible, I would suggest working on the functionality to ensure consistency across all records.

Yeah...I have only added close button because edit button might take little bit of time...as you told I will change the icon and update it

**Comment by BLSowmya** [comment]
I have changed the ❌to 🗑️ please check it

**Comment by KiranAminPanjwani** [comment]
Can you please add the "Edit" functionality as well?

**Pull request closed without merging**
