### PR TITLE
added a login page

### PR DESCRIPTION
**Pull request by Kallind**
## 👨‍💻 Changes proposed: 
Added a login page and changes in css according to the login page

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.
- [x] I am a participant of Hacktoberfest 2022.

### CODE REVIEW

**Comment by Kallind** [comment]
also mades changes in the css file

**Comment by KiranAminPanjwani** [comment]
Thank you so much for the wonderful contribution! Please link the _login.html_ with the _index.html_ by adding a login option for the user on the **homepage**.

**Comment by KiranAminPanjwani** [comment]
It would be great if you could upgrade your forked repository and make some modifications to enhance the design, especially with your login page styling. :-)

**Comment by KiranAminPanjwani** [comment]
> so once i like the login page with the index.html this issue will get resolved right? or you need any other changes?

Yes, after upgrading your repository, link the login page with the index.html so that users can redirect to the login page from the home page.

**Pull request closed without merging**
