### PR TITLE
Update Contact Us page to be more consistent with the styling

### PR DESCRIPTION
**Pull request by n4itik**
## 👨‍💻 Changes proposed: 

- Change the form-img to one with similar color palette as the rest of the UI
- Have the same border radii across all the input fields
- Restrict resizing of the text area
- Change button color for improved contrast

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.
- [x] I am a participant of Hacktoberfest 2023.

## 📷 Screenshots

image

### CODE REVIEW

**Comment by SunilKumar-K** [comment]
It is not responsive for different screens , you can you check it once 🔂.

**Comment by KiranAminPanjwani** [comment]
Could you please make it responsive?

**Comment by n4itik** [comment]
Done!

https://github.com/KiranAminPanjwani/MedStats/assets/66974007/39909b8d-cb80-4b53-9588-5aaa4ffa7e1e

Let me know if you need more breakpoints.

**Comment by KiranAminPanjwani** [comment]
Thank you for the wonderful contribution!✨ Please upgrade your forked repository and resolve any conflicts, so that I can merge your pull request.

**Comment by n4itik** [comment]
Done! 😇

**Pull request merged**
