### PR TITLE
Login page and homepage bug fixes

### PR DESCRIPTION
**Pull request by Hrishit-B**
🛠️ Fixes Issue #8

## 👨‍💻 Changes proposed: 

I have worked on fixing the link to the homepage. Earlier clicking on it gave an alert and then redirected to the home page anyway, even without logging in. Now that issue is fixed

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.
- [ ] I am a participant of Hacktoberfest 2022.

### CODE REVIEW

**Comment by KiranAminPanjwani** [comment]
image

It is still displaying the same alert message. Please double-check it and attach screenshots of the changes you have made in your comment.

**Comment by Hrishit-B** [comment]
image

Here is the change that I have made.

**Comment by KiranAminPanjwani** [comment]
> image
> 
> Here is the change that I have made.

Thank you for your contribution. However, the change you have made does not align with the design theme of the project. Additionally, making such minor adjustments will not significantly enhance the project's value or improve the website's design.

Please consider making further modifications and adding more commits to this PR. Your efforts in this regard will be much appreciated. 😇

**Comment by Hrishit-B** [comment]
No problem. I'll look into other areas of this project that I can work on. Thanks

**Pull request closed without merging**
