### PR TITLE
fix the hardcoded copyright year

### LINKED ISSUE #33: In the footer section, the copyright year should be dynamically generated instead of being statically hardcoded.
### 🎇 Description

@KiranAminPanjwani Right now, the copyright year is written manually, which means someone has to change it whenever a new year begins. However, with just a few lines of code in JavaScript, we can make it automatic. This means that the copyright year will always be up-to-date without anyone having to change it manually. For example, if the current year is 2023, the copyright section will show 2023. And when the year changes to 2024, the copyright section will automatically update to 2024.

### 🖼 Screenshots

Screenshot 2023-10-11 232652

### PR DESCRIPTION
**Pull request by MrDBC**
Closes #33 

- [x ] My code follows the code style of this project.
- [x ] This PR does not contain plagiarized content.
- [x ] The title of my pull request is a short description of the requested changes.
- [ ] I am a participant of Hacktoberfest 2022.

## 📷 Screenshots
image

### CODE REVIEW

**Comment by KiranAminPanjwani** [comment]
image

please remove the gray background color from here.

**Comment by MrDBC** [comment]
> image
> 
> please remove the gray background color from here.


ok @KiranAminPanjwani 
 so the background should be transparent , right?

**Comment by KiranAminPanjwani** [comment]
BTW, the issue wasn't assigned to you.

**Comment by KiranAminPanjwani** [comment]
image
 Please improve footer section.

**Comment by MrDBC** [comment]
@KiranAminPanjwani 
>1. I think we can remove the gap between the login and the footer section
>2. also its best if we can remove the scroll bars 

Do you have anything else in mind? 
like adding a background color to the footer section?

image

**Pull request merged**
