### PR TITLE
#26 Navbar enhanced

### LINKED ISSUE #26: [FEATURE] Creating Navbar for good user experience
### 🎇 Description

As of now, no buttons/hyperlinks are there in Navbar like 'About', 'Contact Us', 'Login' , etc.

we can add some of those with a minimal hover animation to enhance user experience.

### 🖼 Screenshots

Screenshot 2023-10-11 at 12 52 20 PM

### PR DESCRIPTION
**Pull request by JatinBawne**
Closes #26 

MedStats icon has been updates along with hyperlinks in navbar.

### CODE REVIEW

**Comment by JatinBawne** [comment]
@KiranAminPanjwani kindly review and merge

**Comment by KiranAminPanjwani** [comment]
The blue icon is missing, and the responsive design is disturbed.

**Comment by JatinBawne** [comment]
Issue has been resolved.
Kindly review and merge.

**Comment by KiranAminPanjwani** [comment]
Would you kindly consider enhancing the logo rather than using the old image directly?

**Comment by JatinBawne** [comment]
logo-color

@KiranAminPanjwani  how is this??

**Comment by JatinBawne** [comment]
Screenshot 2023-10-11 at 8 17 21 PM

@KiranAminPanjwani  How's this??

**Comment by KiranAminPanjwani** [comment]
Thank you for the wonderful contribution ✨

**Pull request merged**
